import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styles2 from "../styles/Home2.module.css";
import styles3 from "../styles/Home3.module.css";
import Script from "next/script";

import Dummy from "../components/Dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <style jsx>
        {`
          .span1 {
            text-decoration: underline;
            background-color: #f0f0f0;
            border-radius: 0.2vw;
          }
          .span2 {
            text-decoration: underline;
            border-radius: 0.2vw;
          }
        `}
      </style>
      <Head>
        <title>Welcome to NextJS Mastery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/file.js" strategy="lazyOnload"></Script> */}
      <div className="container">
        <div className="col-12">
          <h1
            className={`text-primary text-center ${styles.poppins} ${styles2.bg}`}
          >
            <span className="span1">Hunting Coder</span>
          </h1>
        </div>
        <div className="col-12">
          <h5
            className={`text-light text-center ${styles.poppins} ${styles3.bg}`}
          >
            <span className="span2">
              A blog for hunting coders by a hunting coders
            </span>
          </h5>
        </div>
        <Dummy></Dummy>
        <div className="col-12 text-center">
          <Image
            src="/coder.avif"
            alt="Coder"
            width="828"
            height="552"
            style={{ border: "2px solid white" }}
          />
        </div>

        <div className="col-12 text-light text-center dummy">
          <h1>For Developers By Developers</h1>
        </div>
      </div>
    </>
  );
}
