import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to NextJS Mastery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/file.js" strategy="lazyOnload"></Script> */}
      <nav className={`${styles.mainnav} ${styles.poppins}`}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>AboutUs</li>
          </Link>
          <Link href="/blogs">
            <li>Blogs</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      <h1 className={`text-primary text-center ${styles.poppins}`}>
        Hunting Coder
      </h1>
      <h4 className={`text-light text-center ${styles.poppins}`}>
        A blog for hunting coders by a hunting coders
      </h4>
    </>
  );
}
